version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
      - printenv
      - echo Add a line
  pre_build:
    commands:
      - echo PreBuild started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo PostBuild started on `date`